# pudu_errors.py

PUDU_ERROR_CODES = {
    "SUCCESS": "Операция завершена успешно.",
    "CLOUD_OPEN_UNKNOW_ERROR": "Неизвестная ошибка.",
    "CLOUD_OPEN_ROBOT_DB_ERROR": "Ошибка базы данных робота.",
    "CLOUD_OPEN_ROBOT_PARAM_ERROR": "Ошибка параметров запроса.",
    "CLOUD_OPEN_WAIT": "Предыдущая операция ещё не завершена.",
    "CLOUD_OPEN_ROBOT_UNREGISTER": "Робот не зарегистрирован в облаке.",
    "CLOUD_OPEN_TIMEOUT": "Время ожидания истекло.",
    "CLOUD_OPEN_IOT_SEND_ERROR": "Ошибка отправки IoT-сообщения.",
    "CLOUD_OPEN_ROBOT_INFO_ERROR": "Ошибка получения информации о роботе.",
    "CLOUD_OPEN_ROBOT_NOT_EXISTS": "Робот не найден или не привязан к магазину.",
    "CLOUD_OPEN_GET_STATUS_ERROR": "Не удалось получить статус робота.",
    "CLOUD_OPEN_ROBOT_OFFLINE": "Робот не в сети.",
    "CLOUD_OPEN_CANNOT_SCHEDULE": "Робот не может быть запланирован.",
    "CLOUD_OPEN_ROBOT_IS_CHARGING": "Робот на зарядке.",
    "CLOUD_OPEN_NO_AVAILABLE_ROBOT": "Нет доступных роботов.",
    "CLOUD_OPEN_ENTER_QUEUE_ERROR": "Ошибка при постановке в очередь.",
    "CLOUD_OPEN_CALL_ERROR": "Ошибка вызова робота.",
    "CLOUD_OPEN_ROBOT_EXEC_FAIL": "Робот не смог выполнить задачу.",
    "CLOUD_OPEN_CHECK_QUEUE_FAIL": "Ошибка при проверке очереди.",
    "CLOUD_OPEN_QUEUE_OVER": "Робот стал недоступен и задача завершена.",
    "CLOUD_OPEN_TASK_NOT_EXISTS": "Задача не существует.",
    "CLOUD_OPEN_TASK_BELONG_ERROR": "Нет прав на управление задачей.",
    "CLOUD_OPEN_UNABLE_CANCEL_TASK": "Задача не может быть отменена.",
    "CLOUD_OPEN_QUEUE_CANCEL_FAIL": "Ошибка при отмене из очереди.",
    "CLOUD_OPEN_QUEUE_LIMIT": "Превышено количество вызовов.",
    "CLOUD_OPEN_TASK_EXPIRED": "Задача завершена из-за истечения времени.",
    "CLOUD_OPEN_UNABLE_COMPLETE_TASK": "Невозможно завершить задачу.",
    "CLOUD_OPEN_ROBOT_RSP_ERROR": "Ответ робота имеет неверную структуру.",
    "CLOUD_OPEN_SCREEN_CONTENT_LEN_ERR": "Слишком длинный текст на экране.",
    "CLOUD_OPEN_ROBOT_BELONG_ERROR": "Нет доступа к управлению этим роботом.",
}
